inherit_from: .rubocop_todo.yml
require: rubocop-rspec

AllCops:
  Include:
    - 'lib/**/*.rb'
    - 'spec/**/*.rb'
  Exclude:
    - 'vendor/**/*'
    - 'examples/**/*'
    - 'tmp/**/*'
    - Gemfile
    - Rakefile
    - '*.gemspec'
  DisplayCopNames: true
  TargetRubyVersion: 2.7
  NewCops: enable

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: '{}'

Style/SignalException:
  EnforcedStyle: semantic

Style/RegexpLiteral:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/AndOr:
  EnforcedStyle: conditionals

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Layout/LineLength:
  Max: 100
  AllowedPatterns: ['(^| )\# .*'] # ignore long comments

Metrics/ParameterLists:
  CountKeywordArgs: false

Style/FormatString:
  Enabled: false

Style/EmptyCaseCondition:
  Enabled: false

Lint/AmbiguousOperatorPrecedence:
  Enabled: false

Lint/EmptyWhen:
  Enabled: false

Naming/FileName:
  Exclude:
    - 'lib/yard-junk.rb'

Lint/MixedRegexpCaptureTypes:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/OpenStructUse:
  Enabled: false

# TODO
Style/Documentation:
  Enabled: false
