inherit_from: "../.rubocop.yml"

Style/BlockDelimiters:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Layout/MultilineBlockLayout:
  Enabled: false

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

RSpec:
  Language:
    Includes:
      Examples:
        - its_block
        - its_call

RSpec/DescribeClass:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/BeforeAfterAll:
  Enabled: false

# RSpec/EmptyExampleGroup:
#   CustomIncludeMethods: [its_call, its_block]

RSpec/FilePath:
  Enabled: false

RSpec/ImplicitSubject:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

Layout/BlockEndNewline:
  Enabled: false

# Because
#  expect { ... }
#   .to send_message.with(...)
#   .and send_message.with(...)
Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/LineLength:
  Enabled: false
